sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t michaloo/crystal .

script:
  - VERSION=`docker run --entrypoint /bin/sh michaloo/crystal -c 'echo $CRYSTAL_VERSION'` bash -c '[[ `docker run -it --rm michaloo/crystal version` == *"$VERSION"* ]]'