sudo: required

language: ruby

if: tag IS present

services:
  - docker

before_install:
  - docker build -t michaloo/crystal .

script:
  - bash -c '[[ `docker run -it --rm michaloo/crystal version` == *"$TRAVIS_TAG"* ]]'